# Generated by Django 3.2.5 on 2024-04-17 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=255)),
                ('resenha', models.TextField(max_length=255)),
                ('data_leitura', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
